language: node_js
node_js:
  - '8'
  - 'node'
script:
  - yarn run lint:ci
  - yarn run test:ci
  - yarn run build
after_success:
  - yarn run test:coverage
branches:
  only:
    - master
    - develop
cache: yarn
